List<String> faculty = [
  "Bisnis dan Ekonomi",
  "Humaniora dan Industri Kreatif",
  "Teknologi Industri",
  "Teknik Sipil dan Perencanaan",
  "Keguruan dan Ilmu Pendidikan",
];

List<String> major = [
  "Sastra Inggris",
  "English for Business",
  "English for Creative Industry",
  "Teknik Sipil",
  "Arsitektur",
  "Teknik Elektro",
  "Teknik Industri",
  "International Business Engineering",
  "Informatika",
  "Sistem Informasi Bisnis",
  "Manajemen Bisnis",
  "Manajemen Perhotelan",
  "International Business Management",
  "Manajemen Pariwisata",
  "Manajemen Pemasaran",
  "Manajemen Keuangan",
  "Akuntansi Bisnis",
  "Akuntansi Pajak",
  "International Business Accounting",
  "Desain Interior",
  "Desain Komunikasi Visual",
  "International Program in Digital Media",
  "Fashion Design dan Textile",
  "Bahasa Mandarin",
  "Ilmu Komunikasi",
  "Pendidikan Guru Sekolah Dasar",
  "Pendidikan Guru Pendidikan Anak Usia Dini",
  "Data Science & Analytics",
  "Internet of Things",
  "Sustainable Mechanical Engineering & Design",
  "Automotive",
];
